// Lithuanian labels for OSM `cuisine` tag values (places.poi.attr.cuisine).
// "regional" and "local" both mean "lithuanian" per OSM Lithuania mapping convention.
// Sourced from the full set of distinct values currently in the live DB, not just the
// (smaller) list in the originating issue — new OSM values keep appearing over time,
// so a missing key here just falls back to showing the raw value (see formatCuisine).
export const CUISINE_LABELS: Record<string, string> = {
  american: "amerikietiška",
  armenian: "armėniška",
  asian: "azijietiška",
  bagel: "beigeliai",
  barbecue: "barbekiu",
  breakfast: "pusryčiai",
  bubble_tea: "bumbulinė arbata",
  burger: "burgeriai",
  buschenschank: "vyno smuklė",
  cake: "tortai, pyragai",
  cheburek: "čeburekai",
  chicken: "vištiena",
  chinese: "kinų",
  coffee: "kava",
  coffee_shop: "kavinė",
  crepe: "plonieji blynai",
  donut: "spurgos",
  european: "europietiška",
  fast_food: "greitas maistas",
  fish_and_chips: "žuvis su bulvytėmis",
  french: "prancūzų",
  georgian: "gruzinų",
  german: "vokiečių",
  grill: "grilis",
  heuriger: "vyno smuklė",
  hot_dog: "hot dogai",
  ice_cream: "ledai",
  indian: "indų",
  international: "tarptautinė",
  italian: "itališka",
  japanese: "japonų",
  kebab: "kebabai",
  lithuanian: "lietuviška",
  local: "lietuviška",
  mexican: "meksikiečių",
  middle_eastern: "artimųjų rytų",
  noodles: "makaronų patiekalai",
  pancake: "blynai",
  pasta: "makaronai",
  pizza: "pica",
  polish: "lenkų",
  ramen: "ramenas",
  regional: "lietuviška",
  russian: "rusų",
  salad: "salotos",
  sandwich: "sumuštiniai",
  sausage: "dešrelės",
  savory_pancakes: "sūrūs blynai",
  seafood: "jūros gėrybės",
  steak_house: "steikai",
  sushi: "sušiai",
  tea: "arbata",
  thai: "tajų",
  turkish: "turkų",
  uzbek: "uzbekų",
  waffle: "vafliai",
  zefir: "zefyrai",
};
